yeslist = [
    "yes",
    "yasss",
    "yea",
    "yeah",
    "yep",
    "yeppers",
    "sure",
    "yizzir",
    "sounds good",
    "let's do it",
    "no problem",
    "let's go",
    "absolutely",
    "hell yea",
    "hell yes",
    "ok",
    "a little",
    "good",
    "great",
    "of course",
    "alright",
    "by all means",
    "allright",
    "all right",
    "certainly",
    "def",
    "defs",
    "definitely",
    "good enough",
    "gladly",
    "exactly",
    "naturally",
    "positively",
    "surely",
    "sure thing",
    "true",
    "okay",
    "ok",
    "gd",
    "amen",
    "affirmative",
    "without fail",
    "willingly",
    "very well",
    "unquestionably",
    "nod",
    "fine",
    "agree",
    "aight",
    "all righty",
    "aye",
    "cool",
    "correct",
    "fine",
    "fo sho",
    "forizzle",
    "indeed",
    "indubitably",
    "mhm",
    "right on",
    "right",
    "roger",
    "sure",
    "true dat",
    "uh-huh",
    "way",
    "word",
    "ya",
    "yaaasss",
    "yah",
    "ye",
    "yeah"
    "yeh",
    "yes",
    "yessum",
    "yip"
    "yis",
    "you bet",
    "yup",
    "yus"]

nolist = [
    "no thanks",
    "sorry",
    "reject",
    "pass",
    "not this time",
    "not possible",
    "not now",
    "not at all",
    "not at the moment",
    "nope",
    "no",
    "no never",
    "no way",
    "no thnx",
    "no thanks",
    "no go",
    "no can do",
    "nix",
    "never",
    "nep",
    "nein",
    "negatory",
    "negative",
    "neg",
    "nay",
    "naw",
    "nah", "na",
    "n o",
    "prefer not to",
    "if only",
    "ick",
    "i can't",
    "hell no",
    "fuck no",
    "forget it",
    "false",
    "eww",
    "disagreed",
    "deny",
    "decline",
    "certainly not",
    "not really",
    "cancel",
    "by no means",
    "absolutely not"]

errlist = [
    "?",
    "wut?",
    "not really an answer",
    "uhm",
    "what?",
    "???",
    "pardon?"]
